sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
  - '7'
  - '6'
  - '4'
script:
  - yarn test
  - yarn build
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
  - yarn semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
