// flow-typed signature: b248eb036441b50bbbc2cb02289e84b7
// flow-typed version: <<STUB>>/has-yarn_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'has-yarn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "has-yarn" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "has-yarn/index" {
  declare module.exports: $Exports<"has-yarn">;
}
declare module "has-yarn/index.js" {
  declare module.exports: $Exports<"has-yarn">;
}
